// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const DISABLE_SUPABASE = import.meta.env.VITE_DISABLE_SUPABASE === "true";

const createMockSupabase = () => {
  const chain = () => ({
    select: () => chain(),
    eq: () => chain(),
    maybeSingle: async () => ({ data: null, error: null }),
    order: () => chain(),
    limit: async () => ({ data: [], error: null }),
    delete: () => chain(),
    insert: async () => ({ data: null, error: null }),
  });

  return {
    auth: {
      onAuthStateChange: (_cb: any) => ({
        data: { subscription: { unsubscribe: () => {} } },
      }),
      getSession: async () => ({ data: { session: null } }),
      signOut: async () => ({ error: null }),
      signUp: async () => ({ data: { user: null }, error: null }),
    },
    from: () => chain(),
  } as any;
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase =
  !DISABLE_SUPABASE && SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY
    ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
        auth: {
          storage: localStorage,
          persistSession: true,
          autoRefreshToken: true,
        },
      })
    : createMockSupabase();
